### ISSUE TITLE
Documenting FeatureCollection pbf libraries?

### ISSUE THREAD

**Issue by JosiahParry** [Esri/arcgis-pbf#13]
I've build a Rust crate that parses the FeatureCollection protocol buffer specification. This is used by a new R package as part of the R-ArcGIS Bridge team that processes the FeatureCollect pbf into R native objects using the Rust crate. 

- R package:  https://github.com/R-ArcGIS/arcpbf
- Rust parser crate : https://github.com/R-ArcGIS/arcpbf/tree/main/src/rust/esripbf

Is there a recommended place to document libraries that handle this specification? I know there is a pure JS and typescript example implementation in the repo, but am unsure if there is anything more formal.

**Comment by mmgeorge** [comment]
Not at the moment, this repo is really just for hosting mirroring the spec
