### ISSUE TITLE
esriFieldDateOnly not supported in pbf format

### ISSUE THREAD

**Issue by JosiahParry** [Esri/arcgis-pbf#14]
I've noticed that when processing a pbf from an esriFieldDateOnly, the field value is parsed as `EsriFieldTypeSmallInteger` as opposed to a date type. 

Should the .proto file be updated to reflect this? 

This caused and error downstream in https://github.com/R-ArcGIS/arcpbf/issues/2

**Comment by mmgeorge** [comment]
Installed
