### ISSUE TITLE
Ship TypeScript types (.d.ts) along with JS

### ISSUE THREAD

**Issue by thw0rted** [Esri/arcgis-pbf#3]
It looks like you're providing a `protobufjs` generated client library, created with `pbjs`.  If TypeScript users are going to incorporate this client, they will also need TypeScript typings.  The JSDoc comments in the library have subtly-wrong return types and use some JSDoc tags that TS does not support, among them `@interface`, which means it's impossible to use the interface declarations in consuming code.

So, it would be helpful to include the typings file generated by `pbts` alongside the JS library.  These typings include the interface definitions and also provide more a accurate description of the shape of the exported API.

**Comment by thw0rted** [comment]
If it helps, these are the CLI arguments I used to make my own client + typings:

```sh
./node_modules/protobufjs/bin/pbjs -t static-module -o FeatureCollection.js --es6 -w commonjs --no-create --no-encode --no-convert --no-delimited --force-message FeatureCollection.proto
./node_modules/protobufjs/bin/pbts -o FeatureCollection.d.ts FeatureCollection.js
```

That also cuts down on the size of the library by focusing on decoding, and only for non-delimited messages.

**Comment by odoe** [comment]
Great, these typings have now been added. Thanks!
