### ISSUE TITLE
Result Parsing not working in C#

### ISSUE THREAD

**Issue by shane-pienaar-gbs** [Esri/arcgis-pbf#6]
Hi, and hopefully this is the right forum to be asking this.

I'm trying the following simple workflow in c#, but not getting result:

1. Downloaded the latest [FeatureCollection.proto](https://github.com/Esri/arcgis-pbf/blob/main/proto/FeatureCollection/FeatureCollection.proto)
2. Changed the namespace as follows: option csharp_namespace = "ArcGIS.Protobuf";
2. Compiled it to FeatureCollection.csusing using [protoc.exe](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated): .\protoc-3.15.8-win64\bin\protoc.exe --csharp_out=. .\FeatureCollection.proto
3. Performed a Feature Count to obtain a result.pbf: [https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/buildings_frankfurt/FeatureServer/0/query?where=1%3D1&returnCountOnly=true&f=pbf](https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/buildings_frankfurt/FeatureServer/0/query?where=1%3D1&returnCountOnly=true&f=pbf)
4. Used the following C# pseudo-code (following the [tutorial](https://developers.google.com/protocol-buffers/docs/csharptutorial)) to try and deserialise the result:
>           using static ArcGIS.Protobuf.FeatureCollectionPBuffer;
>           Types.CountResult cr;
>           using (var input = File.OpenRead("results.pbf"))
>           {
>                cr = Types.CountResult.Parser.ParseFrom(input);
>           }
5. No error/exception is thrown, but the resultant object has no value(s).

Am I way off-track?

Thanks

**Comment by mmgeorge** [comment]
@shane-pienaar-gbs I think you want to be picking out the queryResult at the top level, not the countResult:
 
https://github.com/Esri/arcgis-pbf/blob/29b8dadca4823364ea628e4af192fc7e73c02e2c/proto/FeatureCollection/FeatureCollection.proto#L208-L209

https://github.com/Esri/arcgis-pbf/blob/29b8dadca4823364ea628e4af192fc7e73c02e2c/proto/FeatureCollection/FeatureCollection.proto#L196-L202

Order is queryResult -> countResult -> count, e.g.: 

![query-result](https://user-images.githubusercontent.com/16738762/116624275-84501d80-a8fc-11eb-902b-fdbd8c506855.PNG)

**Comment by shane-pienaar-gbs** [comment]
@mmgeorge - thanks for the quick response.

I tried parsing to queryResult as suggested, but get a similar outcome unfortunately:

![image](https://user-images.githubusercontent.com/5591013/116627608-9041eb00-a9a1-11eb-90e2-b94d839ad518.png)

**Comment by mmgeorge** [comment]
Can you do `Types.FeatureCollectionPBuffer.Parser.ParseFrom`? I don't use C# and every pbf lib is a bit different. I can look at setting something up though if you are still running into issues.

**Comment by shane-pienaar-gbs** [comment]
@mmgeorge - That did the trick! Thanks very much for your time. I'll Close with this comment.

![image](https://user-images.githubusercontent.com/5591013/116630070-b322ce00-a9a6-11eb-854e-0e29b8c21714.png)
